---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit the README.Rmd file -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab report #1

Follow the instructions posted at https://ds202-at-isu.github.io/labs.html for the lab assignment. The work is meant to be finished during the lab time, but you have time until Monday evening to polish things.

Include your answers in this document (Rmd file). Make sure that it knits properly (into the md file). Upload both the Rmd and the md file to your repository.  

All submissions to the github repo will be automatically uploaded for grading once the due date is passed.
Submit a link to your repository on Canvas (only one submission per team) to signal to the instructors that you are done with your submission.

THIS IS A LINE FROM RSTUDIO

## Step 12.1

*Alexander:* Git is installed and set up. No problems with the prerequisites

## Step 12.2

## Step 12.3

## Step 12.4

*Alexander:* I was able to connect Git locally through Rstudio. However, I had to find where my computer locally saved the file. I used the "files" tab on the bottom right of Rstudio to see it was located in my "documents" folder.

## Step 12.5 

*Alexander:* At first I was having difficulty with an error when I tried to push. After reading the error it told me that I had to pull first. After doing so I was able to push successfully.

## Step 12.6

## Step 12.7
